In [1]:
import pandas as pd
import numpy as np

dc_listings = pd.read_csv('listings.csv')
dc_reviews = pd.read_csv('reviews.csv')

merged = pd.merge(dc_listings, dc_reviews, on='id', how='inner')

In [2]:
merged.to_csv("merged_master.csv")

In [3]:
merged['id'].nunique()

5180

In [4]:
merged.describe()

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,latitude,longitude,accommodates,bathrooms,...,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,id_2,reviewer_id
count,2.349420e+05,2.349420e+05,2.349420e+05,234942.000000,234942.000000,0.0,234942.000000,234942.000000,234942.000000,0.0,...,234792.000000,234790.000000,0.0,234942.000000,234942.000000,234942.000000,234942.000000,234942.000000,2.349420e+05,2.349420e+05
mean,1.974412e+07,2.022091e+13,8.377927e+07,5.059538,8.293817,NaN,53.353285,-6.253331,3.014697,NaN,...,4.771252,4.689854,NaN,3.804641,2.528918,1.177635,0.016596,2.951309,1.334470e+17,1.191938e+08
std,1.290677e+07,5.324230e+01,9.043192e+07,37.627475,59.604618,NaN,0.049444,0.061794,1.863023,NaN,...,0.178124,0.195200,NaN,7.229503,7.221952,2.224841,0.257585,3.692873,2.487449e+17,1.098915e+08
min,4.407700e+04,2.022091e+13,4.398400e+04,1.000000,1.000000,NaN,53.181730,-6.526020,1.000000,NaN,...,1.000000,0.000000,NaN,1.000000,0.000000,0.000000,0.000000,0.010000,2.037030e+05,1.260000e+02
25%,1.014620e+07,2.022091e+13,1.846608e+07,1.000000,1.000000,NaN,53.336590,-6.275330,2.000000,NaN,...,4.670000,4.590000,NaN,1.000000,0.000000,0.000000,0.000000,1.130000,2.289092e+08,3.276506e+07
50%,1.815116e+07,2.022091e+13,5.081456e+07,2.000000,3.000000,NaN,53.346780,-6.262600,2.000000,NaN,...,4.810000,4.730000,NaN,2.000000,1.000000,1.000000,0.000000,2.200000,4.333919e+08,8.508412e+07
75%,2.658249e+07,2.022091e+13,1.150191e+08,4.000000,5.000000,NaN,53.361090,-6.235420,4.000000,NaN,...,4.910000,4.820000,NaN,3.000000,2.000000,1.000000,0.000000,3.810000,7.048160e+08,1.759773e+08
max,5.439455e+07,2.022091e+13,4.395122e+08,2157.000000,3311.000000,NaN,53.635000,-6.052910,16.000000,NaN,...,5.000000,5.000000,NaN,66.000000,55.000000,66.000000,8.000000,44.720000,7.136610e+17,4.783675e+08

In [3]:
from langdetect import detect
def detectlang(comment):
  try:
    return detect(comment)
  except:
    return 0

merged['detect'] = merged['comments'].apply(lambda comment: detectlang(comment = comment))
merged.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,id_2,date,reviewer_id,reviewer_name,comments,detect
0,44077,https://www.airbnb.com/rooms/44077,20220911231053,2022-09-12,city scrape,cosy comfortable Irish cottage twin,Our house was built in 1937 when there was ple...,I like our neighbourhood as there is no shorta...,https://a0.muscache.com/pictures/525706/050a3a...,193005,...,0,2,0,1.85,203703.0,20/03/2011,393348,Christian,We enjoyed our stay very much. The room was co...,en
1,44077,https://www.airbnb.com/rooms/44077,20220911231053,2022-09-12,city scrape,cosy comfortable Irish cottage twin,Our house was built in 1937 when there was ple...,I like our neighbourhood as there is no shorta...,https://a0.muscache.com/pictures/525706/050a3a...,193005,...,0,2,0,1.85,211369.0,28/03/2011,444004,Solidea,We have been here 4 nights. Stay in a home is ...,en
2,44077,https://www.airbnb.com/rooms/44077,20220911231053,2022-09-12,city scrape,cosy comfortable Irish cottage twin,Our house was built in 1937 when there was ple...,I like our neighbourhood as there is no shorta...,https://a0.muscache.com/pictures/525706/050a3a...,193005,...,0,2,0,1.85,234215.0,21/04/2011,465058,Michael And Isabelle,Teresa and Hughie were great hosts. They were ...,en
3,44077,https://www.airbnb.com/rooms/44077,20220911231053,2022-09-12,city scrape,cosy comfortable Irish cottage twin,Our house was built in 1937 when there was ple...,I like our neighbourhood as there is no shorta...,https://a0.muscache.com/pictures/525706/050a3a...,193005,...,0,2,0,1.85,261843.0,13/05/2011,490005,Weston,"No surprises, was as described. Very gracious...",en
4,44077,https://www.airbnb.com/rooms/44077,20220911231053,2022-09-12,city scrape,cosy comfortable Irish cottage twin,Our house was built in 1937 when there was ple...,I like our neighbourhood as there is no shorta...,https://a0.muscache.com/pictures/525706/050a3a...,193005,...,0,2,0,1.85,268148.0,17/05/2011,520460,Barbara,"Teresa was a lovely hostess, and we had a deli...",en

In [4]:
merged.to_csv("merged_with_lang.csv")

In [5]:
final = merged[merged["detect"] == "en"]
final.to_csv("merged_with_en_comments.csv")

In [6]:
final['comments'] = final['comments'].str.replace(r'[^\d.a-zA-Z]+', " ")
final['comments'] = final['comments'].str.casefold()
final.head()

/var/folders/rd/j5mq0pcd6c3b6ld8pnmj2xnw0000gn/T/ipykernel_1590/1570848099.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  final['comments'] = final['comments'].str.replace(r'[^\d.a-zA-Z]+', " ")
/var/folders/rd/j5mq0pcd6c3b6ld8pnmj2xnw0000gn/T/ipykernel_1590/1570848099.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final['comments'] = final['comments'].str.replace(r'[^\d.a-zA-Z]+', " ")
/var/folders/rd/j5mq0pcd6c3b6ld8pnmj2xnw0000gn/T/ipykernel_1590/1570848099.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final['comments'] = final['comments'].str.casefold()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,id_2,date,reviewer_id,reviewer_name,comments,detect
0,44077,https://www.airbnb.com/rooms/44077,20220911231053,2022-09-12,city scrape,cosy comfortable Irish cottage twin,Our house was built in 1937 when there was ple...,I like our neighbourhood as there is no shorta...,https://a0.muscache.com/pictures/525706/050a3a...,193005,...,0,2,0,1.85,203703.0,20/03/2011,393348,Christian,we enjoyed our stay very much. the room was co...,en
1,44077,https://www.airbnb.com/rooms/44077,20220911231053,2022-09-12,city scrape,cosy comfortable Irish cottage twin,Our house was built in 1937 when there was ple...,I like our neighbourhood as there is no shorta...,https://a0.muscache.com/pictures/525706/050a3a...,193005,...,0,2,0,1.85,211369.0,28/03/2011,444004,Solidea,we have been here 4 nights. stay in a home is ...,en
2,44077,https://www.airbnb.com/rooms/44077,20220911231053,2022-09-12,city scrape,cosy comfortable Irish cottage twin,Our house was built in 1937 when there was ple...,I like our neighbourhood as there is no shorta...,https://a0.muscache.com/pictures/525706/050a3a...,193005,...,0,2,0,1.85,234215.0,21/04/2011,465058,Michael And Isabelle,teresa and hughie were great hosts. they were ...,en
3,44077,https://www.airbnb.com/rooms/44077,20220911231053,2022-09-12,city scrape,cosy comfortable Irish cottage twin,Our house was built in 1937 when there was ple...,I like our neighbourhood as there is no shorta...,https://a0.muscache.com/pictures/525706/050a3a...,193005,...,0,2,0,1.85,261843.0,13/05/2011,490005,Weston,no surprises was as described. very gracious h...,en
4,44077,https://www.airbnb.com/rooms/44077,20220911231053,2022-09-12,city scrape,cosy comfortable Irish cottage twin,Our house was built in 1937 when there was ple...,I like our neighbourhood as there is no shorta...,https://a0.muscache.com/pictures/525706/050a3a...,193005,...,0,2,0,1.85,268148.0,17/05/2011,520460,Barbara,teresa was a lovely hostess and we had a delig...,en

In [7]:
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

all = []
for review in final.comments:
    sid = SentimentIntensityAnalyzer()
    scores = sid.polarity_scores(review)
    all.append(scores['compound'])

final['sentiment'] = all

/var/folders/rd/j5mq0pcd6c3b6ld8pnmj2xnw0000gn/T/ipykernel_1590/1255889465.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final['sentiment'] = all

In [8]:
final.to_csv("en_sent_merged.csv")

In [9]:
final.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,id_2,date,reviewer_id,reviewer_name,comments,detect,sentiment
0,44077,https://www.airbnb.com/rooms/44077,20220911231053,2022-09-12,city scrape,cosy comfortable Irish cottage twin,Our house was built in 1937 when there was ple...,I like our neighbourhood as there is no shorta...,https://a0.muscache.com/pictures/525706/050a3a...,193005,...,2,0,1.85,203703.0,20/03/2011,393348,Christian,we enjoyed our stay very much. the room was co...,en,0.9513
1,44077,https://www.airbnb.com/rooms/44077,20220911231053,2022-09-12,city scrape,cosy comfortable Irish cottage twin,Our house was built in 1937 when there was ple...,I like our neighbourhood as there is no shorta...,https://a0.muscache.com/pictures/525706/050a3a...,193005,...,2,0,1.85,211369.0,28/03/2011,444004,Solidea,we have been here 4 nights. stay in a home is ...,en,0.9804
2,44077,https://www.airbnb.com/rooms/44077,20220911231053,2022-09-12,city scrape,cosy comfortable Irish cottage twin,Our house was built in 1937 when there was ple...,I like our neighbourhood as there is no shorta...,https://a0.muscache.com/pictures/525706/050a3a...,193005,...,2,0,1.85,234215.0,21/04/2011,465058,Michael And Isabelle,teresa and hughie were great hosts. they were ...,en,0.9836
3,44077,https://www.airbnb.com/rooms/44077,20220911231053,2022-09-12,city scrape,cosy comfortable Irish cottage twin,Our house was built in 1937 when there was ple...,I like our neighbourhood as there is no shorta...,https://a0.muscache.com/pictures/525706/050a3a...,193005,...,2,0,1.85,261843.0,13/05/2011,490005,Weston,no surprises was as described. very gracious h...,en,0.9447
4,44077,https://www.airbnb.com/rooms/44077,20220911231053,2022-09-12,city scrape,cosy comfortable Irish cottage twin,Our house was built in 1937 when there was ple...,I like our neighbourhood as there is no shorta...,https://a0.muscache.com/pictures/525706/050a3a...,193005,...,2,0,1.85,268148.0,17/05/2011,520460,Barbara,teresa was a lovely hostess and we had a delig...,en,0.9821